{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.data",
    "module": "micronaut-data-bom",
    "version": "3.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-document-model",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-document-processor",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-hibernate-jpa",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-hibernate-reactive",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-jdbc",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-model",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-mongodb",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-processor",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-r2dbc",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-runtime",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-spring",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-spring-jpa",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-tx",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-tx-hibernate",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-document-model",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-document-processor",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-hibernate-jpa",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-hibernate-reactive",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-jdbc",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-model",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-mongodb",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-processor",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-r2dbc",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-runtime",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-spring",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-spring-jpa",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-tx",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-tx-hibernate",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-data-bom-3.8.1-SNAPSHOT.toml",
          "url": "micronaut-data-bom-3.8.1-SNAPSHOT.toml",
          "size": 2051,
          "sha512": "9084bd80ac05c01a555570cba4af07c59579d79b98ad17785fe407f7a984891f2c3798128e16efd7e12699b18a5a5a4ac161fd285e83f4b3190755d5025e4983",
          "sha256": "a0d178f44575aeb141e98815b936a5759785852abe353db99c0a2dd264122743",
          "sha1": "086558136d79f9b5f9558cc8408bf4848c8fceea",
          "md5": "30db27bc516aa31370749dd8cb09f61c"
        }
      ]
    }
  ]
}
