{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.data",
    "module": "micronaut-data-model",
    "version": "3.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-tx",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-aop",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "micronaut-data-model-3.8.1-SNAPSHOT.jar",
          "url": "micronaut-data-model-3.8.1-SNAPSHOT.jar",
          "size": 517116,
          "sha512": "d337e1f6e2c06a4bea27bad10854cbdf35369252762b36ddb880e20de30f04a8c6b9bb72504cc91433f9f9e22972c518ffa4faa0dc1b29c07f31009a2bc2602e",
          "sha256": "8397b994ddeeddbf558c8bedeb183d7edbbbd00978ffd9e0d70cf3527dfc3cb0",
          "sha1": "47d7c3c821be557e6ffffeb503f8f343b9da4d95",
          "md5": "2f0547f00d9ace4a69fed232b42804a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.18"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-tx",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-aop",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "micronaut-data-model-3.8.1-SNAPSHOT.jar",
          "url": "micronaut-data-model-3.8.1-SNAPSHOT.jar",
          "size": 517116,
          "sha512": "d337e1f6e2c06a4bea27bad10854cbdf35369252762b36ddb880e20de30f04a8c6b9bb72504cc91433f9f9e22972c518ffa4faa0dc1b29c07f31009a2bc2602e",
          "sha256": "8397b994ddeeddbf558c8bedeb183d7edbbbd00978ffd9e0d70cf3527dfc3cb0",
          "sha1": "47d7c3c821be557e6ffffeb503f8f343b9da4d95",
          "md5": "2f0547f00d9ace4a69fed232b42804a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-data-model-3.8.1-SNAPSHOT-sources.jar",
          "url": "micronaut-data-model-3.8.1-SNAPSHOT-sources.jar",
          "size": 352439,
          "sha512": "96461972d9ee29f517613298dccf93db80283963e8c30e3322b77fb54914ad3d82e72cad70f663813fd6d9fb5706e2b9bb31b49c359c0c5aba01f4c8c8397b97",
          "sha256": "ffa4ed901a4ec33581a53ddbe74ef1656199287afeeefecab8223ccf391223b9",
          "sha1": "16b1196166f4441d595c6afd9579e7b0701a8bca",
          "md5": "ac6604db68eeb617ccba8a2b9f2cb775"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-data-model-3.8.1-SNAPSHOT-javadoc.jar",
          "url": "micronaut-data-model-3.8.1-SNAPSHOT-javadoc.jar",
          "size": 1384845,
          "sha512": "105874d8ce30914eb0167759c0ea5813aa49330942ce69969de9050b599ae1d91c54e19867e0a613a8157e4a83513ec961c04add730a91c695e7520ce875eeb5",
          "sha256": "71f32e27fec0c51af1822c631b2d283ea0b092e2ce85ab7cc6296d2f75ace312",
          "sha1": "79a24f8f519624bf1555fd0986a224748605da1a",
          "md5": "63dd4bc62c5b017e162e93bb759295d7"
        }
      ]
    }
  ]
}
