{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.data",
    "module": "micronaut-data-jdbc",
    "version": "3.8.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-runtime",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "micronaut-data-jdbc-3.8.1-SNAPSHOT.jar",
          "url": "micronaut-data-jdbc-3.8.1-SNAPSHOT.jar",
          "size": 116241,
          "sha512": "945b20b3ef6a5ae0f0e4e247341f8c0320ab17649a733fb0bdac6cec5e9dcd0d54eb12a8f21a67aa6c83ce0af977506577e41d52ab50a5924f986fd7ea6ea89d",
          "sha256": "19b1e1f7344870855d28d952d50563aa2c72d41d283bbc74dec3185e1093292e",
          "sha1": "88a523e4c097a43d7f399bbc58fe82972024a1a1",
          "md5": "df2ca09de449ed4a19054ac90840017b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.micronaut.data",
          "module": "micronaut-data-runtime",
          "version": {
            "requires": "3.8.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "micronaut-data-jdbc-3.8.1-SNAPSHOT.jar",
          "url": "micronaut-data-jdbc-3.8.1-SNAPSHOT.jar",
          "size": 116241,
          "sha512": "945b20b3ef6a5ae0f0e4e247341f8c0320ab17649a733fb0bdac6cec5e9dcd0d54eb12a8f21a67aa6c83ce0af977506577e41d52ab50a5924f986fd7ea6ea89d",
          "sha256": "19b1e1f7344870855d28d952d50563aa2c72d41d283bbc74dec3185e1093292e",
          "sha1": "88a523e4c097a43d7f399bbc58fe82972024a1a1",
          "md5": "df2ca09de449ed4a19054ac90840017b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-data-jdbc-3.8.1-SNAPSHOT-sources.jar",
          "url": "micronaut-data-jdbc-3.8.1-SNAPSHOT-sources.jar",
          "size": 34437,
          "sha512": "588b7dd556f0a575a30dcbaa16c9982a286e66fca98d92be80d5f978be8976a78ff83e0993fa0ac6392d13fc1cbd5d1419be1780d5abd13f3f8973e6e13c9b27",
          "sha256": "41e4e501e697d5eda5ae74173e031895ffa2eb28c503ba1e1e0e875f5b96ed87",
          "sha1": "4124ba21ad44f4b66da615d178b6b7dc77668723",
          "md5": "4ab4fff8686a1f8ac5e0177c2064e5b5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-data-jdbc-3.8.1-SNAPSHOT-javadoc.jar",
          "url": "micronaut-data-jdbc-3.8.1-SNAPSHOT-javadoc.jar",
          "size": 202027,
          "sha512": "f12e788ee7644de435169f902ded97e49d757b7a19f6527d2e2bee9419fc0c9ab7423a0d3f439b028cd1b37203f40810269a0223327056d22dae49da4d033d5c",
          "sha256": "aee50b033871411f6b50a78b473a09fb52ed5ba770a49d54a157f51444d71267",
          "sha1": "4d3cfd237ae69e7cee57e6b74799325a66b5fc40",
          "md5": "7436fd15269e91f31ccbee7875c52b4f"
        }
      ]
    }
  ]
}
